# Generated by Django 4.0 on 2021-12-27 11:41

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('thumbnail', models.FileField(upload_to='uploads/project/preview/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('file', models.FileField(upload_to=blog.models.file_path_dir)),
                ('size', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('parent_dir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='blog.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('thumbnail', models.FileField(upload_to='uploads/project/preview/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.project')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directories', to='blog.event'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_dirs', to='blog.directory'),
        ),
    ]
