# Generated by Django 4.0 on 2021-12-17 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(default='text', upload_to=''),
            preserve_default=False,
        ),
    ]
