# Generated by Django 4.0 on 2021-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_directory_id_alter_event_id_alter_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.FileField(upload_to='project/preview/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(upload_to='project/preview/'),
        ),
    ]
