# Generated by Django 4.0 on 2021-12-28 18:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_event_thumbnail_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.file_path_dir),
        ),
    ]
