# Generated by Django 4.0 on 2021-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_project_created_at_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(upload_to='uploads/project/'),
        ),
    ]
