# Generated by Django 4.0 on 2022-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_file_preview_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview_compressed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
