# Generated by Django 4.0 on 2021-12-21 17:20

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('thumbnail', models.FileField(upload_to=blog.models.file_path_dir)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.event')),
            ],
        ),
    ]
