# Generated by Django 4.0 on 2021-12-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.directory'),
        ),
    ]
