# Generated by Django 4.0 on 2021-12-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_directory_parent_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='parent_directory',
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_dirs', to='blog.directory'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directories', to='blog.event'),
        ),
    ]
