# Generated by Django 4.0 on 2021-12-23 18:42

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_directory_parent_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('file', models.FileField(upload_to=blog.models.project_path_dir)),
                ('parent_dir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.directory')),
            ],
        ),
    ]
