# Generated by Django 4.0 on 2021-12-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='blog.directory'),
        ),
    ]
